#Welcome :
welcometitle: "§k§4|§r§eW§gelcome§k§4|§r" #Title For Send
welcomesubtitle: "§k§4|§r§e@ReAlHiTlEr§k§4|§r" #SubTitle For Send
#Form :
formtitle: "§k§4|§r§eW§gelcome§k§4|§r" #Title For UI
formcontent: "§4| §eRules :\n1 -\n2 -\n3 - §4|§r" #Content For UI
closebutton: "§k§4|§r§cClose§k§4|§r" #Close Button For UI
